language: node_js
before_script: 
node_js:
- 0.1
deploy:
  provider: heroku
  app: poman
  strategy: git
  api_key:
    secure: LMelv6YKBiunY0oZt00EF/kxs2gp/80gb84yGEEe65EpQOMZdBJDFs9ZJiAIWxHHCkhetfAqeO/tVZutefCxxCbXOT/jbrj89r1Bq9HfrP9kdPsa5lVaFzMSKSsmVLqtTD/c/Fq8n9DIPQfmbsDgWqAb2D2azzYNc8VtETQhMWo=
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
